require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AeroplanesController do

  # This should return the minimal set of attributes required to create a valid
  # Aeroplane. As you add validations to Aeroplane, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AeroplanesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all aeroplanes as @aeroplanes" do
      aeroplane = Aeroplane.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aeroplanes).should eq([aeroplane])
    end
  end

  describe "GET show" do
    it "assigns the requested aeroplane as @aeroplane" do
      aeroplane = Aeroplane.create! valid_attributes
      get :show, {:id => aeroplane.to_param}, valid_session
      assigns(:aeroplane).should eq(aeroplane)
    end
  end

  describe "GET new" do
    it "assigns a new aeroplane as @aeroplane" do
      get :new, {}, valid_session
      assigns(:aeroplane).should be_a_new(Aeroplane)
    end
  end

  describe "GET edit" do
    it "assigns the requested aeroplane as @aeroplane" do
      aeroplane = Aeroplane.create! valid_attributes
      get :edit, {:id => aeroplane.to_param}, valid_session
      assigns(:aeroplane).should eq(aeroplane)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Aeroplane" do
        expect {
          post :create, {:aeroplane => valid_attributes}, valid_session
        }.to change(Aeroplane, :count).by(1)
      end

      it "assigns a newly created aeroplane as @aeroplane" do
        post :create, {:aeroplane => valid_attributes}, valid_session
        assigns(:aeroplane).should be_a(Aeroplane)
        assigns(:aeroplane).should be_persisted
      end

      it "redirects to the created aeroplane" do
        post :create, {:aeroplane => valid_attributes}, valid_session
        response.should redirect_to(Aeroplane.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aeroplane as @aeroplane" do
        # Trigger the behavior that occurs when invalid params are submitted
        Aeroplane.any_instance.stub(:save).and_return(false)
        post :create, {:aeroplane => { "name" => "invalid value" }}, valid_session
        assigns(:aeroplane).should be_a_new(Aeroplane)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Aeroplane.any_instance.stub(:save).and_return(false)
        post :create, {:aeroplane => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested aeroplane" do
        aeroplane = Aeroplane.create! valid_attributes
        # Assuming there are no other aeroplanes in the database, this
        # specifies that the Aeroplane created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Aeroplane.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => aeroplane.to_param, :aeroplane => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested aeroplane as @aeroplane" do
        aeroplane = Aeroplane.create! valid_attributes
        put :update, {:id => aeroplane.to_param, :aeroplane => valid_attributes}, valid_session
        assigns(:aeroplane).should eq(aeroplane)
      end

      it "redirects to the aeroplane" do
        aeroplane = Aeroplane.create! valid_attributes
        put :update, {:id => aeroplane.to_param, :aeroplane => valid_attributes}, valid_session
        response.should redirect_to(aeroplane)
      end
    end

    describe "with invalid params" do
      it "assigns the aeroplane as @aeroplane" do
        aeroplane = Aeroplane.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Aeroplane.any_instance.stub(:save).and_return(false)
        put :update, {:id => aeroplane.to_param, :aeroplane => { "name" => "invalid value" }}, valid_session
        assigns(:aeroplane).should eq(aeroplane)
      end

      it "re-renders the 'edit' template" do
        aeroplane = Aeroplane.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Aeroplane.any_instance.stub(:save).and_return(false)
        put :update, {:id => aeroplane.to_param, :aeroplane => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aeroplane" do
      aeroplane = Aeroplane.create! valid_attributes
      expect {
        delete :destroy, {:id => aeroplane.to_param}, valid_session
      }.to change(Aeroplane, :count).by(-1)
    end

    it "redirects to the aeroplanes list" do
      aeroplane = Aeroplane.create! valid_attributes
      delete :destroy, {:id => aeroplane.to_param}, valid_session
      response.should redirect_to(aeroplanes_url)
    end
  end

end
